apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: shop
  labels:
    app: catalog
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
  - name: http
    port: 8080
    targetPort: 8080
