apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
  namespace: shop
  labels:
    app: catalog
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=
